= 🧠 Tabaqui

**Tabaqui** is a code snippet extractor designed for collecting annotated method-level and field-level code samples from a Java project and exporting them in a structured format (JSON or YAML) for AI training purposes.

'''

== 📦 Overview

This tool scans Java source files for custom annotations and extracts:

- The **question**
- The **answer**
- The **class/method/field code**

and serializes them into a machine-readable format like:

[source,json]
----
[
  {
    "instruction": "What does this method do?",
    "input": "",
    "output": "It pauses Kafka fetcher: protected void doSuspend() { ... }"
  }
]
----

== User guide

To use this project, you need to add the Annotation API repository and inject dependency into the pom file of the project you want to extract code snippets from. This https://github.com/LostArtist/ai-annotations-api[Annotation API] will allow you to annotate the code:

[source, xml]
----
<repositories>
  <repository>
    <id>github</id>
    <url>https://maven.pkg.github.com/LostArtist/annotation-api</url>
  </repository>
</repositories>

<dependency>
  <groupId>org.tabaqui</groupId>
  <artifactId>annotation-api</artifactId>
  <version>1.0.5</version>
</dependency>
----



There are two types of annotations:

[source,java]
----
@AiSnippet(question = "your_question", answer = "your_answer")
----

This one will extract the question and the answer with the annotated class/method/field code.

[source,java]
----
@AiAutoSnippet(question = "your_question")
----

This one will generate a templated answer for you, like "The method {method} from the class {class} is responsible for this operation".

After you annotate all the necessary code in the project, you will be able to extract snippets running the .jar file in the api module of this project:

=== Example:
[source, ]
----
java -jar api/target/tabaqui-jar-with-dependencies.jar --project ~/code/java/camel/components/camel-kafka --format json
----

=== Parameters:

**-p, --project** - path to the project +
**-f, --format** - output file format (json, yaml)

The output file will be placed in the tabaqui directory.

=== Snippet conversion:

After snippet extraction, you will have the snippets.json or snippets.yaml file. These should be converted into the form of taxonomy, recognizable by InstructLab. For this purpose, use the convert_json_to_qna.py or convert_yaml_to_qna.py script:

[source, ]
----
./convert_json_to_qna.py snippets.json qna.yaml

./convert_yaml_to_qna.py snippets.yaml qna.yaml
----

This will create a qna.yaml file that you can add as a compositional skill into your model for generating synthetic data.

